## YAML Template.
---
name: DropChest
main: DropChest.DropChest
version: 0.99
commands:
   DropChest:
      description: Main command for DropChest
      usage: /DropChest chance/location arguments
      permission: ChestDrop.DropChest
      permission-message: You don't have ChestDrop.DropChest